INSERT INTO users(first_name, last_name, email, password, salt,), VALUES
("Jakob",       "Sensenig", "Jacob_Sensenig@baylor.edu", ),
("Jonathan",    "Hehn",     "jonathan.hehn@gmail.com",     ),
("Jan",         "Kraybill", "Jkraybill@Cofchrist.Org", ),
("Hilary",      "Donaldson","hilaryseraph@hotmail.com", ),
("Swee Hong",   "Lim",      "lshshl@gmail.com",),
("Stephen",     "Cowden",   "stephenacowden@gmail.com",),
("David",       "Bjorlin",  "Davidbjorlin@gmail.com",),
("Ginny",       "Chilton",  "ginny.chilton@gmail.com",      ),
("Cathy",       "Toole",    "ktoole@outlook.com",           ),
("Duane",       "Toole",    "duane.toole@gmail.com" ,       ),
("Colleen",     "Toole",    "colleen.toole@gmail.com",      ),
("Alex",        "Mejias",   "alex@highstreethymns.com",     ),
("Adam",        "Kukuk",    "adam@adamkukuk.com",           ),
("Paul",        "Richardson","parichar@samford.edu",        ),
("Crystal",     "Jonkman",  "cjonkman@verizon.net",         ),
("Crystal Bailes", "Lennon","crysco13@gmail.com",           ),
("Nelson",      "Cowan",    "ncowan@bu.edu",                ),
("Lydia",       "Pedersen", "lydia.pedersen@sympatico.ca",  ),
("Tina",        "Schneider","schneider.290@osu.edu",        ),
("Edward Ed",   "Frazier",  "eddiejfra@aol.com",            ),
("Mel",         "Bringle",  "mbringle@brevard.edu",         ),
("Nancy",       "Graham",   "nanlgraham@gmail.com",         ),
("Sylvia",      "Hook",     "sylvia.d.hook@gmail.com",      ),
("Judy Brown",  "Richardson","libravet@aol.com" ,           ),
("Lynn and Tim","Anderson", "celebrad@gmail.com",           ),
("Kola",        "Adebiyi",  "koladebiyi@gmail.com",         ),
("Frank",       "Kulash",   "fkulash@gmail.com",            ),
("Dudley",      "Weaver",   "dudley.weaver@gmail.com",      ),
("Brittney",    "Stephan",  "brittney.stephan@garrett.edu", ),
("Adrienne",    "Tindall",  "a.tindall@comcast.net",        ),
("Cathy",       "Salika",   "csalika@illinois.edu",         ),
("Joe",         "Noelliste","Joe_Noelliste@baylor.edu",     );
