branch-defaults:
  master:
    environment: production
global:
  application_name: hymndb-client
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: us-west-2
  profile: eb-cli
  repository: null
  sc: git
